GET http://localhost:3000/api/menu_items
###
GET http://localhost:3000/api/menu_items/22
###

POST http://localhost:3000/api/menu_items 
Content-Type: application/json

{
    "name": "Pierogi ruskie",
    "price": 12.99,
    "ingredients": "Z ziemniakami i koperkiem",
    "category": "obiad"
}
###
PUT  http://localhost:3000/api/menu_items/pomidor
###
DELETE http://localhost:3000/api/menu_items/pomidor