GET http://localhost:3000/api/user

###

POST  http://localhost:3000/api/user
Content-Type: application/json

{
    "name": "admin",
    "password": "123",
    "isUserLogged": false,
    "order": [],
    "isOrderSended": false 
}
###

PATCH   http://localhost:3001/api/order/65295a86267183aeb067c407
Content-Type: application/json

{
    "isOrderCompleted": false
}
###
DELETE http://localhost:3001/api/order/65292a41eb031803a6f279c6
